-- @description Dantepog_Icons
-- @author Dantepog
-- @version 1.0
-- @changelog
--   1.0 Initial Release

-- @about
--   # Dantepog_Icons
--
--   Custom Dantepog toolbar icons .
-- @provides
--  [data] *.png