-- @description Dantepog_Icons
-- @author Dantepog
-- @version 1.0
-- @changelog
--   1.0 Initial Release
-- @about
--   # Dantepog_Icons
--
--   Custom dantepog toolbar icons.
-- @provides
--  [data] toolbar_icons/**/*.png